export const impactMetrics = [
  {
    name: 'Plastic Bottles Saved',
    slug: 'plastic-bottles-saved',
    unit: 'bottles',
    iconName: 'bottle',
    description: 'Number of single-use plastic bottles avoided by choosing reusable alternatives',
    comparison: "That's {value} weeks of single-use plastic avoided!",
    sortOrder: 1,
    isActive: true,
  },
  {
    name: 'Single-Use Items Replaced',
    slug: 'single-use-items-replaced',
    unit: 'items',
    iconName: 'recycle',
    description: 'Disposable items replaced by reusable eco-friendly alternatives',
    comparison: 'Equivalent to {value} months of disposable items!',
    sortOrder: 2,
    isActive: true,
  },
  {
    name: 'Carbon Offset',
    slug: 'carbon-offset',
    unit: 'kg CO2',
    iconName: 'leaf',
    description: 'Kilograms of CO2 offset through sustainable product choices',
    comparison: 'Like planting {value} trees for a year!',
    sortOrder: 3,
    isActive: true,
  },
  {
    name: 'Trees Planted',
    slug: 'trees-planted',
    unit: 'trees',
    iconName: 'tree',
    description: 'Trees planted through our partnership with reforestation organizations',
    comparison: '{value} kg of CO2 absorbed per year!',
    sortOrder: 4,
    isActive: true,
  },
  {
    name: 'Water Saved',
    slug: 'water-saved',
    unit: 'liters',
    iconName: 'droplet',
    description: 'Liters of water saved by choosing products with lower water footprints',
    comparison: "That's {value} showers worth of water!",
    sortOrder: 5,
    isActive: true,
  },
  {
    name: 'Waste Diverted',
    slug: 'waste-diverted',
    unit: 'kg',
    iconName: 'trash',
    description: 'Kilograms of waste diverted from landfills through reusable products',
    comparison: '{value} pounds kept out of landfills!',
    sortOrder: 6,
    isActive: true,
  },
];

// Product impact data (mapping product titles to their impact values)
export const productImpactData: Record<string, Record<string, number>> = {
  'Bamboo Water Bottle': {
    'plastic-bottles-saved': 365,
    'single-use-items-replaced': 365,
    'carbon-offset': 2.5,
    'waste-diverted': 0.5,
  },
  'Reusable Produce Bags - Set of 5': {
    'single-use-items-replaced': 500,
    'carbon-offset': 1.0,
    'waste-diverted': 0.3,
  },
  'Bamboo Cutlery Set': {
    'single-use-items-replaced': 200,
    'carbon-offset': 1.5,
    'waste-diverted': 0.2,
  },
  'Natural Loofah Sponge - 3 Pack': {
    'single-use-items-replaced': 36,
    'carbon-offset': 0.5,
    'waste-diverted': 0.1,
  },
  'Beeswax Food Wraps': {
    'single-use-items-replaced': 300,
    'carbon-offset': 1.0,
    'waste-diverted': 0.2,
  },
  'Bamboo Toothbrush Set': {
    'single-use-items-replaced': 4,
    'carbon-offset': 0.3,
    'waste-diverted': 0.05,
  },
  'Stainless Steel Lunch Container': {
    'single-use-items-replaced': 250,
    'carbon-offset': 2.0,
    'waste-diverted': 0.4,
  },
  'Wool Dryer Balls - Set of 6': {
    'single-use-items-replaced': 1000,
    'carbon-offset': 1.0,
    'waste-diverted': 0.3,
  },
  'Bamboo Bathroom Set': {
    'plastic-bottles-saved': 3,
    'single-use-items-replaced': 10,
    'carbon-offset': 0.8,
    'waste-diverted': 0.2,
  },
  'Reusable Coffee Filter': {
    'single-use-items-replaced': 500,
    'carbon-offset': 0.5,
    'water-saved': 100,
    'waste-diverted': 0.2,
  },
  'Natural Cleaning Kit': {
    'plastic-bottles-saved': 10,
    'single-use-items-replaced': 20,
    'carbon-offset': 1.5,
    'water-saved': 50,
    'waste-diverted': 0.3,
  },
  'Bamboo Dish Brush': {
    'single-use-items-replaced': 12,
    'carbon-offset': 0.2,
    'waste-diverted': 0.05,
  },
  'Organic Cotton Napkins - Set of 8': {
    'single-use-items-replaced': 1000,
    'carbon-offset': 0.8,
    'water-saved': 200,
    'waste-diverted': 0.4,
  },
  'Compost Bin with Charcoal Filter': {
    'carbon-offset': 50,
    'waste-diverted': 100,
  },
  'Glass Food Storage Set': {
    'single-use-items-replaced': 500,
    'carbon-offset': 2.0,
    'waste-diverted': 0.5,
  },
};
