export const quizQuestions = [
  {
    visibleId: 'q1',
    question: 'What area of your life do you want to make more sustainable?',
    questionType: 'SINGLE_CHOICE',
    options: JSON.stringify([
      { value: 'kitchen', label: 'Kitchen' },
      { value: 'bathroom', label: 'Bathroom' },
      { value: 'personal-care', label: 'Personal Care' },
      { value: 'cleaning', label: 'Cleaning' },
      { value: 'all', label: 'All of the above' },
    ]),
    orderIndex: 1,
    categoryFilter: null,
    isActive: true,
  },
  {
    visibleId: 'q2',
    question: "What's your experience with eco-friendly products?",
    questionType: 'SINGLE_CHOICE',
    options: JSON.stringify([
      { value: 'beginner', label: "Beginner - I'm just getting started" },
      { value: 'some-experience', label: "Some experience - I've tried a few products" },
      { value: 'eco-expert', label: 'Eco-expert - Sustainability is my lifestyle' },
    ]),
    orderIndex: 2,
    categoryFilter: null,
    isActive: true,
  },
  {
    visibleId: 'q3',
    question: 'What matters most to you? (Select all that apply)',
    questionType: 'MULTIPLE_CHOICE',
    options: JSON.stringify([
      { value: 'plastic-free', label: 'Plastic-free packaging' },
      { value: 'vegan', label: 'Vegan & cruelty-free' },
      { value: 'organic', label: 'Organic & natural ingredients' },
      { value: 'budget-friendly', label: 'Budget-friendly options' },
    ]),
    orderIndex: 3,
    categoryFilter: null,
    isActive: true,
  },
  {
    visibleId: 'q4',
    question: 'Any allergies or sensitivities?',
    questionType: 'MULTIPLE_CHOICE',
    options: JSON.stringify([
      { value: 'fragrance-free', label: 'Fragrance-free preferred' },
      { value: 'nut-free', label: 'Nut-free required' },
      { value: 'none', label: 'No allergies or sensitivities' },
    ]),
    orderIndex: 4,
    categoryFilter: null,
    isActive: true,
  },
  {
    visibleId: 'q5',
    question: 'How many people are in your household?',
    questionType: 'SINGLE_CHOICE',
    options: JSON.stringify([
      { value: '1', label: 'Just me' },
      { value: '2-3', label: '2-3 people' },
      { value: '4+', label: '4 or more people' },
    ]),
    orderIndex: 5,
    categoryFilter: null,
    isActive: true,
  },
];
